service: src

provider:
  name: aws
  runtime: dotnetcore2.1
  region: us-west-2

package:
  artifact: bin/Debug/netcoreapp2.1/deploy-package.zip

functions:
  api:
    handler: src::src.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY